global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nestjs-app'
    metrics_path: '/api/v2/metrics'
    static_configs:
      - targets: ['host.docker.internal:3300', 'host.docker.internal:3001']
